# Generated by Django 4.1 on 2022-09-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0003_alter_photo_id_alter_room_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="lat",
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name="room",
            name="lng",
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
    ]
